### PR TITLE
[DEV-435]: Add protos for chat settings

### PR DESCRIPTION
**Pull request by vmanikes**

### CODE REVIEW

**Comment by vncntd** [comment]
Just leaving here a global comment about something I think about.

When creating a channel - I think we automatically want to add the settings part of the channel creation page - so wdyt about a function similar to `initChatSettings` taking just the channel_id as parameter and configuring all the settings based on default values ?

**Review by vncntd — APPROVED** [review]
Feel free to either merge or modify based on my comment !

**Comment by vmanikes** [comment]
Totally, I was thinking that reset will do the same thing what you said. May be I will rename reset function to init?

**Comment by vncntd** [comment]
Not good idea, indeed ! Good for me 🚀

**Pull request merged**
